#!/usr/bin/env python
import sys
import zstd
import argparse


def main(input_file):
    data = zstd.decompress(input_file.read())
    print (data.decode())


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '-i', '--input-file', type=argparse.FileType('rb'),
        default=(None if sys.stdin.isatty() else sys.stdin.buffer)
    )
    args = parser.parse_args()
    main(args.input_file)
